apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven
  labels:
    app.kubernetes.io/version: "0.3"
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
spec:
  description: >
    This Task can be used to run a Maven build. It uses a workspace to store m2 local repo.

  workspaces:
    - name: source
      description: The workspace consisting of maven project.
    - name: maven-settings
      description: >
        The workspace consisting of the custom maven settings provided by the user.
    - name: maven-local-repo
      description: Local repo (m2) workspace
      optional: false

  params:
    - name: MAVEN_IMAGE
      type: string
      description: Maven base image
      default: gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
    - name: GOALS
      type: array
      description: Maven goals to run
      default:
        - "package"
    - name: MAVEN_MIRROR_URL
      type: string
      default: ""
    - name: SERVER_USER
      type: string
      default: ""
    - name: SERVER_PASSWORD
      type: string
      default: ""
    - name: PROXY_USER
      type: string
      default: ""
    - name: PROXY_PASSWORD
      type: string
      default: ""
    - name: PROXY_PORT
      type: string
      default: ""
    - name: PROXY_HOST
      type: string
      default: ""
    - name: PROXY_NON_PROXY_HOSTS
      type: string
      default: ""
    - name: PROXY_PROTOCOL
      type: string
      default: "http"
    - name: CONTEXT_DIR
      type: string
      default: "."

  steps:
    - name: mvn-settings
      image: registry.access.redhat.com/ubi8/ubi-minimal:8.2
      script: |
        #!/usr/bin/env bash

        [[ -f $(workspaces.maven-settings.path)/settings.xml ]] && \
        echo "using existing $(workspaces.maven-settings.path)/settings.xml" && exit 0

        cat > "$(workspaces.maven-settings.path)/settings.xml" <<EOF
        <settings>
          <servers>
            <!-- ### SERVER's USER INFO from ENV ### -->
          </servers>
          <mirrors>
            <!-- ### mirrors from ENV ### -->
          </mirrors>
          <proxies>
            <!-- ### HTTP proxy from ENV ### -->
          </proxies>
        </settings>
        EOF

        xml=""
        if [ -n "$(params.PROXY_HOST)" ] && [ -n "$(params.PROXY_PORT)" ]; then
          xml="<proxy><id>genproxy</id><active>true</active><protocol>$(params.PROXY_PROTOCOL)</protocol><host>$(params.PROXY_HOST)</host><port>$(params.PROXY_PORT)</port>"
          if [ -n "$(params.PROXY_USER)" ] && [ -n "$(params.PROXY_PASSWORD)" ]; then
            xml="$xml<username>$(params.PROXY_USER)</username><password>$(params.PROXY_PASSWORD)</password>"
          fi
          if [ -n "$(params.PROXY_NON_PROXY_HOSTS)" ]; then
            xml="$xml<nonProxyHosts>$(params.PROXY_NON_PROXY_HOSTS)</nonProxyHosts>"
          fi
          xml="$xml</proxy>"
          sed -i "s|<!-- ### HTTP proxy from ENV ### -->|$xml|" "$(workspaces.maven-settings.path)/settings.xml"
        fi

        if [ -n "$(params.SERVER_USER)" ] && [ -n "$(params.SERVER_PASSWORD)" ]; then
          xml="<server><id>serverid</id><username>$(params.SERVER_USER)</username><password>$(params.SERVER_PASSWORD)</password></server>"
          sed -i "s|<!-- ### SERVER's USER INFO from ENV ### -->|$xml|" "$(workspaces.maven-settings.path)/settings.xml"
        fi

        if [ -n "$(params.MAVEN_MIRROR_URL)" ]; then
          xml="<mirror><id>mirror.default</id><url>$(params.MAVEN_MIRROR_URL)</url><mirrorOf>central</mirrorOf></mirror>"
          sed -i "s|<!-- ### mirrors from ENV ### -->|$xml|" "$(workspaces.maven-settings.path)/settings.xml"
        fi

    - name: mvn-goals
      image: $(params.MAVEN_IMAGE)
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      command:
        - mvn
      args:
        - -s
        - $(workspaces.maven-settings.path)/settings.xml
        - -Dmaven.repo.local=$(workspaces.maven-local-repo.path)/.m2
        - "$(params.GOALS[*])"
