---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven
spec:
  description: Run a Maven build
  workspaces:
    - name: source
    - name: maven-settings
  params:
    - name: MAVEN_IMAGE
      type: string
      default: gcr.io/cloud-builders/mvn:3.9.6
    - name: GOALS
      type: array
      default: ["package"]
    - name: CONTEXT_DIR
      type: string
      default: "."
    - name: SUBPATH
      type: string
      default: "default"
  results:
    - name: group-id
      type: string
    - name: artifact-id
      type: string
    - name: version
      type: string
  steps:
    - name: build
      image: $(params.MAVEN_IMAGE)
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      command: ["/usr/bin/mvn"]
      args:
        - -s
        - $(workspaces.maven-settings.path)/settings.xml
        - $(params.GOALS[*])
        - "-Dmaven.repo.local=/custom/.m2"
      volumeMounts:
        - name: m2-volume
          mountPath: /custom/.m2
          subPath: $(params.SUBPATH)
  volumes:
    - name: m2-volume
      persistentVolumeClaim:
        claimName: maven-local-m2-pvc
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test-mvn-results
spec:
  params:
    - name: input
      type: string
  steps:
    - name: show-results
      image: registry.access.redhat.com/ubi8/ubi-minimal
      script: |
        #!/bin/bash
        echo "Maven Task Results:"
        echo "$(params.input)"
