apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven
  labels:
    app.kubernetes.io/version: "0.4"
  annotations:
    tekton.dev/pipelines.minVersion: "0.50.0"
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
spec:
  description: >-
    This Task can be used to run a Maven build. It uses manual volume mounting for local repo.
  workspaces:
    - name: source
      description: The workspace consisting of maven project.
    - name: maven-settings
      description: The workspace consisting of the custom maven settings.
  params:
    - name: MAVEN_IMAGE
      type: string
      description: Maven base image
      default: gcr.io/cloud-builders/mvn:3.9.6
    - name: GOALS
      type: array
      default:
        - package
    - name: CONTEXT_DIR
      type: string
      default: "."
    - name: SUBPATH
      type: string
      description: Sub-directory in shared .m2 PVC
      default: "default"
  results:
    - name: group-id
      type: string
    - name: artifact-id
      type: string
    - name: version
      type: string
  steps:
    - name: build
      image: $(params.MAVEN_IMAGE)
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      command: ["/usr/bin/mvn"]
      args:
        - -s
        - $(workspaces.maven-settings.path)/settings.xml
        - $(params.GOALS[*])
        - "-Dmaven.repo.local=/custom/.m2"
      volumeMounts:
        - name: m2-volume
          mountPath: /custom/.m2
          subPath: $(params.SUBPATH)
  volumes:
    - name: m2-volume
      persistentVolumeClaim:
        claimName: maven-local-m2-pvc
